# Generated by Django 6.0.7 on 2026-07-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boiler',
            name='selected_stage_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='boiler',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='boiler',
            name='capacity_kw',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='boiler',
            name='fuel_type',
            field=models.CharField(default='GAS', max_length=50),
        ),
    ]
