# Generated by Django 6.0.7 on 2026-08-07 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_boiler_selected_stage_ids_alter_boiler_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='products.product'),
        ),
    ]
