# Generated by Django 6.0.7 on 2026-08-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_recipe_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(default='Nomsiz Retseptura', max_length=255),
        ),
    ]
