# Generated by Django 6.0.7 on 2026-07-27 05:32

import core.base_model
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.CharField(default=core.base_model.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('organization_id', models.CharField(blank=True, max_length=36, null=True)),
                ('branch_id', models.CharField(blank=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_id', models.CharField(blank=True, max_length=36, null=True)),
                ('updated_by_id', models.CharField(blank=True, max_length=36, null=True)),
                ('purchase_number', models.CharField(max_length=50, unique=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('order_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('exchange_rate_at_creation', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('supplier', models.ForeignKey(db_column='supplier_id', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='master_data.supplier')),
                ('warehouse', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='master_data.warehouse')),
            ],
            options={
                'db_table': 'purchases',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.CharField(default=core.base_model.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('organization_id', models.CharField(blank=True, max_length=36, null=True)),
                ('branch_id', models.CharField(blank=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_id', models.CharField(blank=True, max_length=36, null=True)),
                ('updated_by_id', models.CharField(blank=True, max_length=36, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='products.product')),
                ('purchase', models.ForeignKey(db_column='purchase_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.purchase')),
            ],
            options={
                'db_table': 'purchase_items',
            },
        ),
    ]
