# Generated by Django 6.0.7 on 2026-07-27 05:32

import core.base_model
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.CharField(default=core.base_model.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('organization_id', models.CharField(blank=True, max_length=36, null=True)),
                ('branch_id', models.CharField(blank=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_id', models.CharField(blank=True, max_length=36, null=True)),
                ('updated_by_id', models.CharField(blank=True, max_length=36, null=True)),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('target_quantity', models.IntegerField()),
                ('completed_quantity', models.IntegerField(default=0)),
                ('defect_quantity', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='PLANNED', max_length=30)),
                ('boiler', models.ForeignKey(db_column='boiler_id', on_delete=django.db.models.deletion.CASCADE, related_name='production_batches', to='products.boiler')),
            ],
            options={
                'db_table': 'production_batches',
            },
        ),
    ]
