# Generated by Django 6.0.7 on 2026-08-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_productionoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionbatch',
            name='assigned_employee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
