# Generated by Django 6.0.7 on 2026-08-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='auto_discount_on_late',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='order',
            name='late_discount_rate',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
        ),
    ]
