# Generated by Django 6.0.7 on 2026-08-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_order_auto_discount_on_late_order_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_employee_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_employee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
