# Generated by Django 6.0.7 on 2026-07-27 05:32

import core.base_model
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.CharField(default=core.base_model.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('organization_id', models.CharField(blank=True, max_length=36, null=True)),
                ('branch_id', models.CharField(blank=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_id', models.CharField(blank=True, max_length=36, null=True)),
                ('updated_by_id', models.CharField(blank=True, max_length=36, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.CharField(default=core.base_model.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('organization_id', models.CharField(blank=True, max_length=36, null=True)),
                ('branch_id', models.CharField(blank=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_id', models.CharField(blank=True, max_length=36, null=True)),
                ('updated_by_id', models.CharField(blank=True, max_length=36, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('permissions', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'positions',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.CharField(default=core.base_model.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('branch_id', models.CharField(blank=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_id', models.CharField(blank=True, max_length=36, null=True)),
                ('updated_by_id', models.CharField(blank=True, max_length=36, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='accounts.organization')),
            ],
            options={
                'db_table': 'branches',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=core.base_model.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_id', models.CharField(blank=True, max_length=36, null=True)),
                ('updated_by_id', models.CharField(blank=True, max_length=36, null=True)),
                ('username', models.CharField(db_index=True, max_length=100, unique=True)),
                ('hashed_password', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(default='EMPLOYEE', max_length=50)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('salary_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('salary_type_id', models.CharField(blank=True, max_length=36, null=True)),
                ('hire_date', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.ForeignKey(blank=True, db_column='branch_id_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.branch')),
                ('organization', models.ForeignKey(blank=True, db_column='organization_id_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.organization')),
                ('position', models.ForeignKey(blank=True, db_column='position_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.position')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.CharField(default=core.base_model.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('organization_id', models.CharField(blank=True, max_length=36, null=True)),
                ('branch_id', models.CharField(blank=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_id', models.CharField(blank=True, max_length=36, null=True)),
                ('updated_by_id', models.CharField(blank=True, max_length=36, null=True)),
                ('refresh_token', models.CharField(db_index=True, max_length=500)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('expires_at', models.CharField(max_length=100)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.user')),
            ],
            options={
                'db_table': 'user_sessions',
            },
        ),
    ]
