# Generated by Django 6.1.1 on 2026-09-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_branch_id_user_organization_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organization_id',
        ),
    ]
