# Generated by Django 6.0.7 on 2026-07-27 05:32

import core.base_model
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.CharField(default=core.base_model.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('organization_id', models.CharField(blank=True, max_length=36, null=True)),
                ('branch_id', models.CharField(blank=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_id', models.CharField(blank=True, max_length=36, null=True)),
                ('updated_by_id', models.CharField(blank=True, max_length=36, null=True)),
                ('transaction_number', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('expense_type', models.ForeignKey(blank=True, db_column='expense_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='master_data.expensetype')),
            ],
            options={
                'db_table': 'financial_transactions',
            },
        ),
    ]
