# Generated by Django 6.0.7 on 2026-07-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_salarytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarytype',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
