# Generated by Django 6.0.7 on 2026-08-03 05:40

import core.base_model
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_currency_defectreason_permissionsmatrix_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.CharField(default=core.base_model.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('organization_id', models.CharField(blank=True, max_length=36, null=True)),
                ('branch_id', models.CharField(blank=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_id', models.CharField(blank=True, max_length=36, null=True)),
                ('updated_by_id', models.CharField(blank=True, max_length=36, null=True)),
                ('service_number', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('boiler_id', models.CharField(blank=True, max_length=100, null=True)),
                ('boiler_model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('service_type_id', models.CharField(blank=True, max_length=100, null=True)),
                ('service_type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_employee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('service_date', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.CharField(default='NORMAL', max_length=50)),
                ('status', models.CharField(default='NEW', max_length=50)),
                ('is_under_warranty', models.BooleanField(default=True)),
                ('warranty_period', models.CharField(blank=True, max_length=100, null=True)),
                ('sale_date', models.CharField(blank=True, max_length=50, null=True)),
                ('order_number', models.CharField(blank=True, max_length=100, null=True)),
                ('production_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_tickets',
            },
        ),
    ]
