# Generated by Django 6.0.7 on 2026-08-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_serviceticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='sale_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='sale_invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
