# Generated by Django 6.0.7 on 2026-08-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_serviceticket_sale_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='employee_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='service_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
