from rest_framework import serializers

class MasterDataCreateSerializer(serializers.Serializer):
    code = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    name = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    title = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    company_name = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    supplier_name = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    description = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    contact_name = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    phone = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    email = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    address = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    location = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    category_id = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    category_name = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    category = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    sequence = serializers.IntegerField(required=False, allow_null=True, default=0)
    months = serializers.FloatField(required=False, allow_null=True)
    duration = serializers.FloatField(required=False, allow_null=True)
    symbol = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    amount = serializers.FloatField(required=False, allow_null=True, default=0.0)
    short_name = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    shortName = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="")
    affects_finance = serializers.BooleanField(required=False, allow_null=True, default=False)
    affectsFinance = serializers.BooleanField(required=False, allow_null=True, default=False)
    rate_to_usd = serializers.FloatField(required=False, allow_null=True, default=1.0)
    exchange_rate = serializers.FloatField(required=False, allow_null=True, default=1.0)
    is_default = serializers.BooleanField(required=False, allow_null=True, default=False)
    stage_order = serializers.IntegerField(required=False, allow_null=True, default=1)
    default_price = serializers.FloatField(required=False, allow_null=True, default=0.0)
    status = serializers.CharField(required=False, allow_null=True, allow_blank=True, default="ACTIVE")
    service_number = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    customer_id = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    customer_name = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    boiler_id = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    boiler_model_name = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    service_type_id = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    service_type_name = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    assigned_employee_id = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    assigned_employee_name = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    service_date = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    priority = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    is_under_warranty = serializers.BooleanField(required=False, allow_null=True)
    warranty_period = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    sale_date = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    order_number = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    production_number = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    notes = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    sale_id = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    sale_invoice_number = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    service_cost = serializers.FloatField(required=False, default=0.0)
    employee_cost = serializers.FloatField(required=False, default=0.0)

class MasterDataUpdateSerializer(serializers.Serializer):
    name = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    title = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    company_name = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    description = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    contact_name = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    phone = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    email = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    address = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    location = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    sequence = serializers.IntegerField(required=False, allow_null=True)
    months = serializers.FloatField(required=False, allow_null=True)
    duration = serializers.FloatField(required=False, allow_null=True)
    symbol = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    amount = serializers.FloatField(required=False, allow_null=True)
    short_name = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    shortName = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    affects_finance = serializers.BooleanField(required=False, allow_null=True)
    affectsFinance = serializers.BooleanField(required=False, allow_null=True)
    rate_to_usd = serializers.FloatField(required=False, allow_null=True)
    exchange_rate = serializers.FloatField(required=False, allow_null=True)
    is_default = serializers.BooleanField(required=False, allow_null=True)
    stage_order = serializers.IntegerField(required=False, allow_null=True)
    default_price = serializers.FloatField(required=False, allow_null=True)
    status = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    service_number = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    customer_id = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    customer_name = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    boiler_id = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    boiler_model_name = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    service_type_id = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    service_type_name = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    assigned_employee_id = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    assigned_employee_name = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    service_date = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    priority = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    is_under_warranty = serializers.BooleanField(required=False, allow_null=True)
    warranty_period = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    sale_date = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    order_number = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    production_number = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    notes = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    sale_id = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    sale_invoice_number = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    service_cost = serializers.FloatField(required=False)
    employee_cost = serializers.FloatField(required=False)

class MasterDataResponseSerializer(serializers.Serializer):
    id = serializers.CharField()
    code = serializers.CharField(allow_null=True, required=False)
    name = serializers.CharField(allow_null=True, required=False)
    description = serializers.CharField(allow_null=True, required=False)
    contact_name = serializers.CharField(allow_null=True, required=False)
    phone = serializers.CharField(allow_null=True, required=False)
    email = serializers.CharField(allow_null=True, required=False)
    address = serializers.CharField(allow_null=True, required=False)
    location = serializers.CharField(allow_null=True, required=False)
    sequence = serializers.IntegerField(allow_null=True, required=False, default=0)
    months = serializers.FloatField(allow_null=True, required=False)
    duration = serializers.FloatField(allow_null=True, required=False)
    symbol = serializers.CharField(allow_null=True, required=False)
    amount = serializers.FloatField(allow_null=True, required=False)
    short_name = serializers.CharField(allow_null=True, required=False)
    shortName = serializers.CharField(allow_null=True, required=False)
    affects_finance = serializers.BooleanField(allow_null=True, required=False)
    affectsFinance = serializers.BooleanField(allow_null=True, required=False)
    rate_to_usd = serializers.FloatField(allow_null=True, required=False)
    exchange_rate = serializers.FloatField(allow_null=True, required=False)
    is_default = serializers.BooleanField(allow_null=True, required=False)
    stage_order = serializers.IntegerField(allow_null=True, required=False)
    default_price = serializers.FloatField(allow_null=True, required=False)
    status = serializers.CharField(allow_null=True, required=False)
    created_at = serializers.DateTimeField()
    updated_at = serializers.DateTimeField()
    service_number = serializers.CharField(allow_null=True, required=False)
    customer_id = serializers.CharField(allow_null=True, required=False)
    customer_name = serializers.CharField(allow_null=True, required=False)
    boiler_id = serializers.CharField(allow_null=True, required=False)
    boiler_model_name = serializers.CharField(allow_null=True, required=False)
    service_type_id = serializers.CharField(allow_null=True, required=False)
    service_type_name = serializers.CharField(allow_null=True, required=False)
    assigned_employee_id = serializers.CharField(allow_null=True, required=False)
    assigned_employee_name = serializers.CharField(allow_null=True, required=False)
    service_date = serializers.CharField(allow_null=True, required=False)
    priority = serializers.CharField(allow_null=True, required=False)
    is_under_warranty = serializers.BooleanField(allow_null=True, required=False)
    warranty_period = serializers.CharField(allow_null=True, required=False)
    sale_date = serializers.CharField(allow_null=True, required=False)
    order_number = serializers.CharField(allow_null=True, required=False)
    production_number = serializers.CharField(allow_null=True, required=False)
    notes = serializers.CharField(allow_null=True, required=False)
    sale_id = serializers.CharField(allow_null=True, required=False)
    sale_invoice_number = serializers.CharField(allow_null=True, required=False)
    service_cost = serializers.FloatField(required=False)
    employee_cost = serializers.FloatField(required=False)
    created_at = serializers.DateTimeField()
    updated_at = serializers.DateTimeField()

    def to_representation(self, instance):
        ret = super().to_representation(instance)
        # Dynamic mapping for Unit symbol -> short_name
        if hasattr(instance, 'symbol'):
            ret['short_name'] = instance.symbol
            ret['shortName'] = instance.symbol

        # Dynamic mapping for Currency exchange_rate -> rate_to_usd
        if hasattr(instance, 'exchange_rate'):
            ret['rate_to_usd'] = float(instance.exchange_rate)
            ret['exchange_rate'] = float(instance.exchange_rate)

        # Dynamic mapping for WarrantyType months -> duration
        if hasattr(instance, 'months'):
            ret['duration'] = int(instance.months)
            ret['duration_months'] = int(instance.months)

        return ret


class CompanyUpdateSerializer(serializers.Serializer):
    name = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    phone = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    website = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    address = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    description = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    currency = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    timezone = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    date_format = serializers.CharField(required=False, allow_null=True, allow_blank=True)

class CompanyResponseSerializer(serializers.Serializer):
    id = serializers.CharField()
    name = serializers.CharField()
    phone = serializers.CharField(allow_null=True, required=False)
    website = serializers.CharField(allow_null=True, required=False)
    address = serializers.CharField(allow_null=True, required=False)
    description = serializers.CharField(allow_null=True, required=False)
    currency = serializers.CharField()
    timezone = serializers.CharField()
    date_format = serializers.CharField()
